### ISSUE TITLE
这个项目还在吗

### ISSUE THREAD

**Issue by icexmoon** [chinesehuazhou/peps-cn#5]
RT，发现有些译文链接已经不在了。

**Comment by icexmoon** [comment]
如果这个项目不维护了的话我打算再开一个中文PEP项目，发现这个项目有一些不足：
1. 没有版权声明，对分享分发有所不妥，比如有个链接翻译就声明不能转载。
2. 译文内容链接到第三方，第三方网站挂了就没了，内容应该使用markdown托管到Github项目本地仓库。

**Comment by icexmoon** [comment]
已经创建了新的项目<https://github.com/icexmoon/PEP-CN>，希望不吝赐教，目前这个项目只有我一个人，还希望能多多扩散

**Comment by chinesehuazhou** [comment]
> RT，发现有些译文链接已经不在了。

哪些不在了？存档挺久了，当时看有几篇没翻译完，格式也很乱，所以直接贴了外部链接。还有几篇应该是来自公众号的，没问到授权，所以也是贴了链接

**Comment by chinesehuazhou** [comment]
> 已经创建了新的项目https://github.com/icexmoon/PEP-CN，希望不吝赐教，目前这个项目只有我一个人，还希望能多多扩散

这个项目也只是我一个人，翻译了几篇。最近没心思翻，很久没更新，你要是不嫌弃，倒是可以合并过来（我有公众号，经常会宣传一下。遗憾的是一直没人响应）

**Comment by icexmoon** [comment]
> > 已经创建了新的项目[https://github.com/icexmoon/PEP-CN，希望不吝赐教，目前这个项目只有我一个人，还希望能多多扩散](https://github.com/icexmoon/PEP-CN%EF%BC%8C%E5%B8%8C%E6%9C%9B%E4%B8%8D%E5%90%9D%E8%B5%90%E6%95%99%EF%BC%8C%E7%9B%AE%E5%89%8D%E8%BF%99%E4%B8%AA%E9%A1%B9%E7%9B%AE%E5%8F%AA%E6%9C%89%E6%88%91%E4%B8%80%E4%B8%AA%E4%BA%BA%EF%BC%8C%E8%BF%98%E5%B8%8C%E6%9C%9B%E8%83%BD%E5%A4%9A%E5%A4%9A%E6%89%A9%E6%95%A3)
> 
> 这个项目也只是我一个人，翻译了几篇。最近没心思翻，很久没更新，你要是不嫌弃，倒是可以合并过来（我有公众号，经常会宣传一下。遗憾的是一直没人响应）

好啊好啊，你可以看下哪些你翻了我没翻的，整理成markdown文件直接发我项目里

**Comment by icexmoon** [comment]
> > 已经创建了新的项目[https://github.com/icexmoon/PEP-CN，希望不吝赐教，目前这个项目只有我一个人，还希望能多多扩散](https://github.com/icexmoon/PEP-CN%EF%BC%8C%E5%B8%8C%E6%9C%9B%E4%B8%8D%E5%90%9D%E8%B5%90%E6%95%99%EF%BC%8C%E7%9B%AE%E5%89%8D%E8%BF%99%E4%B8%AA%E9%A1%B9%E7%9B%AE%E5%8F%AA%E6%9C%89%E6%88%91%E4%B8%80%E4%B8%AA%E4%BA%BA%EF%BC%8C%E8%BF%98%E5%B8%8C%E6%9C%9B%E8%83%BD%E5%A4%9A%E5%A4%9A%E6%89%A9%E6%95%A3)
> 
> 这个项目也只是我一个人，翻译了几篇。最近没心思翻，很久没更新，你要是不嫌弃，倒是可以合并过来（我有公众号，经常会宣传一下。遗憾的是一直没人响应）

额，如果两个项目合并的话我还是推荐我自己的，因为我定义的翻译规矩相对完善一点，包括格式和版权声明，所有翻译成果也会以markdown文件托管，当然了，现在没有人加入一起搞就是了....
